spring:
  application:
    name: MeminiAwardAPI


# MongoDB configuration
spring.data.mongodb:
  uri: mongodb://mb-dev.it:27017/meminiAward
  user: meminiawardapp
  password: Pisojkas!3

# Spring Security configuration

  # Other security properties as needed

# Spring Boot Logging configuration (optional)
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    # Customize logging levels as needed

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days